[phases.setup]
nixPkgs = ["nodejs_22", "python311", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["npm install --build-from-source"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.cjs"
